<?xml version="1.0" encoding="utf-8"?><Database Name="db_sekolah-fadlan" Class="AppDbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-FDMC7DB;Initial Catalog=db_sekolah-fadlan;Integrated Security=True" SettingsObjectName="sekolahku_jude.Properties.Settings" SettingsPropertyName="db_sekolah_fadlanConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_guru" Member="tb_gurus">
    <Type Name="tb_guru">
      <Column Name="guru_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="guru_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_mapel" Member="tb_mapels">
    <Type Name="tb_mapel">
      <Column Name="mapel_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mapel_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>